### PR TITLE
Fix method name in tree.rb

### PR DESCRIPTION
**Pull request by alyssais**

### CODE REVIEW

**Comment by dometto** [comment]
Is this currently leading to errors? If so, should we add a spec to prevent the relevant errors?

**Comment by dometto** [comment]
And thanks again for the PR!

**Comment by alyssais** [comment]
Yeah, causes a `NoMethodError`. I'll add a spec.

**Comment by alyssais** [comment]
On my machine, it looks like there are already failing specs, which this fixes (possibly unnoticed because CI is broken?)

**Comment by bartkamphorst** [comment]
Okay, in that case let's just merge this PR.

**Pull request merged**
