### PR TITLE
Add ability to specify git_dir to repo.

### PR DESCRIPTION
**Pull request by andersonmills**
With this commit, an option, git_dir, specified to the Repo class will
allow it to have a non-standard git_dir.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Thanks @andersonmills . I hadn't even realized that git supports this. :smile:  I have no objections to a change like this. You, @dometto ?

**Comment by dometto** [comment]
I think this is nice, but we should document clearly what the option does exactly. For example, if am I right that this is supposed to work only with non-bare repos (so that the working dir is in one place, and the git dir somewhere else), it should be clear that the `:git_dir` option will be ignored if `:bare` is false.

**Comment by bartkamphorst** [comment]
Agreed!

**Comment by dometto** [comment]
@andersonmills: I think we ourselves should take of the docs (also more generally), so if you add a spec we will merge this. Thanks!

**Comment by andersonmills** [comment]
@dometto @bartkamphorst Excellent. My work has given this second priority in my queue, so I'm hoping to get to it at the end of next week. And, yes, this should only affect non-bare repos.

**Comment by andersonmills** [comment]
Okay, here are a couple of tests which should cover the changes. (Hope getting rid of the trailing whitespace along with that isn't a problem.)

@dometto re-reading your comment above, yes, this works only with non-bare repos. The `:git_dir` option will be ignored if `:bare` is *true* (not false).

**Comment by bartkamphorst** [comment]
Good stuff, thanks for your work on this! My only concern with the tests as they are now is that `expect(new_repo).to_not be_bare` doesn't actually show that the repo object is functional, only that it exists and that the `bare` flag is set to `false`. There's no need of course to test all repo functionality with this non-standardly initialized repo, but it would be good to show that the repo object can access commits for example from a non-standard location.

**Comment by dometto** [comment]
Perhaps it is enough to add an expectation that new_repo.valid?

On 27 jan. 2016, at 23:29, Bart Kamphorst <notifications@github.com<mailto:notifications@github.com>> wrote:


Good stuff, thanks for your work on this! My only concern with the tests as they are now is that expect(new_repo).to_not be_bare doesn't actually show that the repo object is functional, only that it exists and that the bare flag is set to false. There's no need of course to test all repo functionality with this non-standardly initialized repo, but it would be good to show that the repo object can access commits for example from a non-standard location.

**Comment by bartkamphorst** [comment]
> Perhaps it is enough to add an expectation that new_repo.valid?

Yes, good suggestion!

**Comment by andersonmills** [comment]
I added an expectation that the repo be valid. I had to do it before the directories were removed, but that seems to work fine.

**Comment by bartkamphorst** [comment]
Thanks. I think this is then ready to be merged. @dometto, Any other thoughts before I do?

**Comment by dometto** [comment]
:+1:

**Comment by andersonmills** [comment]
@bartkamphorst - Just to point out, also, if the git_dir is a relative path, then it is expected to be inside the work tree. My coworker pointed out that if the git_dir is inside the work tree, then it almost certainly will be .git. It is only when it is outside the work tree that it would be unsurprising for it to be a differently named directory. I can make another quick PR to fix this behavior.

**Comment by bartkamphorst** [comment]
I'm okay with the behavior as is, but if you think it will improve user experience, feel free!

**Pull request merged**
