### PR TITLE
Upgraded JGit lib from v.4.6.1 to v.4.7.0.

### PR DESCRIPTION
**Pull request by rykov**
Another monthly bump

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Gem `v.4.7.0.0` was just released. Thanks @rykov !

**Comment by dometto** [comment]
Looks like this broke the specs though: https://travis-ci.org/repotag/rjgit/jobs/219430233 :(

**Comment by bartkamphorst** [comment]
Tests passed (and still pass) locally though.

**Comment by dometto** [comment]
Not sure what the deal was. Restarted Travis and it works now. Thanks @rykov!

**Comment by rykov** [comment]
I can't seem to find your broken build, but mine failed once too due to a
file name conflict.  The name had a timestamp, so I assumed it was a race
condition and reran without a problem.  Didn't get a chance to investigate.

**Comment by dometto** [comment]
That must have been it -- I restarted the broken job on Travis and it went
alright.

**Comment by rykov** [comment]
To clarify, the race condition comes from the test files, not jGit itself.

**Pull request merged**
