### PR TITLE
Upgrade java version

### PR DESCRIPTION
**Pull request by bartkamphorst**
Breaking change since RJGit would now require JDK 8.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
@rykov Thanks! To be honest, I hadn't seen your PR prior to submitting mine. If you mirror the changes to `.travis.yml` in your PR and the tests pass, I'll happily merge yours instead of mine so that you'll get the github credits for contributing (only fair)!

**Comment by rykov** [comment]
@bartkamphorst Thanks! I've just included the `.travis.yml` updates into #37

**Comment by rykov** [comment]
@bartkamphorst Looks like all test are ok.  Please merge and release when you get a chance.

**Comment by bartkamphorst** [comment]
Thanks. I see that, but I'd like @dometto to okay dropping JDK7.

**Comment by dometto** [comment]
...suddenly unsure whether you get a notification for using the 👍 feature, so: 👍.

**Comment by bartkamphorst** [comment]
No, only notifications for comments. :smile:

**Pull request closed without merging**
